feat: adiciona autenticação via token
tchaguitos/glicobuddy pull request #32
Opened 2022-11-25 20:42 UTC by tchaguitos

2022-11-27 23:49 UTC, nephi-dev requested changes

2022-11-27 23:49 UTC, nephi-dev commented on contextos/glicemias/pontos_de_entrada/api.py
>      bus = barramento.bootstrap(uow=uow)
aqui ta brabo, mas eu traria o UOW como uma dependencia tb, na vdd ter apenas ela e o usuario vir como atributo dessa uow

2022-11-27 23:49 UTC, nephi-dev commented on contextos/usuarios/adaptadores/jwt.py
>  SEGREDO = "73f8a6d421cffdd587c4c8489124760b4ff6b23bf45017d1de417db63533439b"
vai pro .env isso kkkk

2022-11-27 23:49 UTC, nephi-dev commented on contextos/usuarios/adaptadores/jwt.py
> +
classe sem documentação, nem implementação não tem pq existir, coloca um `docs` pra coitada kk

2022-11-27 23:49 UTC, nephi-dev commented on contextos/usuarios/pontos_de_entrada/api.py
>          )
bom lembrar que por padrao, o `bearer` deve ser usado como `Bearer` com o `B` maiúsculo, mas se for só enum ta suave

2022-11-27 23:49 UTC, nephi-dev commented on tests/contextos/usuarios/adaptadores/test_jwt.py
> +    assert payload.get("data_de_nascimento")
da pra trocar para um `all` aqui, 1 assert é mais performático que 5

2022-11-29 22:47 UTC, tchaguitos commented on contextos/glicemias/pontos_de_entrada/api.py
>      bus = barramento.bootstrap(uow=uow)
beeeem melhor assim! valeu demais mano :rocket:

2022-11-29 22:47 UTC, tchaguitos commented on contextos/usuarios/adaptadores/jwt.py
> +
entao, criei mais pra ter uma exceção personalizada, mas realmente ela é totalmente aleatória aí huauhahua :(

2022-11-29 22:49 UTC, tchaguitos commented
@nephi-dev revisei os pontos que você levantou. muito obrigado pelo review e por ter tirado um tempinho. tamo junto man :heart::rocket:

2022-11-29 23:18 UTC, merged